In [41]:
import pandas as pd 
import numpy as np
from datetime import datetime, date

In [42]:
from aind_data_access_api.document_db import MetadataDbClient

API_GATEWAY_HOST = "api.allenneuraldynamics.org"
DATABASE = 'metadata_index'
COLLECTION = 'data_assets'

docdb_api_client = MetadataDbClient(
   host=API_GATEWAY_HOST,
   database=DATABASE,
   collection=COLLECTION,
)
print(docdb_api_client._base_url)

https://api.allenneuraldynamics.org/v1/metadata_index/data_assets

In [49]:
aggregate = [
  {
    "$match": {
      "data_description.project_name": "Dynamic Routing", 
      "data_description.data_level": "derived", 
      "processing.data_processes": {
        "$elemMatch": {
          "process_type": "File format conversion",
          "start_date_time": {"$regex": "^2026-08-04"}
        }
      }
    }
  },
  {
    "$project": {
      "name": 1, 
      "subject_id": "$data_description.subject_id",
      "genotype": "$subject.genotype", 
      "date_of_birth": "$subject.date_of_birth", 
      "sex": "$subject.sex",  
      "session_start_time": "$acquisition.acquisition_start_time",
      "session_end_time": "$acquisition.acquisition_end_time", 
      "stimulus_epochs": "$session.stimulus_epochs.stimulus_name", 
      "project_name": "$data_description.project_name", 
      "modality": "$data_description.modalities.name"
          }
  },
]
    
records = docdb_api_client.aggregate_docdb_records(
    pipeline=aggregate,
)

In [50]:
df = pd.DataFrame(records)
df

,_id,name,subject_id,genotype,date_of_birth,sex,session_start_time,session_end_time,project_name,modality
0,897335f6-895c-455e-89c4-667d86a4304e,ecephys_662892_2023-08-24_14-28-28_nwb_2026-08...,662892,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2022-12-24,Female,2023-08-24T14:28:28-07:00,2023-08-24T16:28:14.588745Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
1,65c0b92b-02d1-479c-82dd-bf8ff10a9af1,ecephys_713655_2024-08-09_10-41-47_nwb_2026-08...,713655,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-11-23,Male,2024-08-09T10:41:47-07:00,2024-08-09T12:49:52.580059Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
2,c4ec72da-c795-4da8-a498-3531a621ddc0,ecephys_664851_2023-11-16_12-54-53_nwb_2026-08...,664851,Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-01-09,Female,2023-11-16T12:54:53-08:00,2023-11-16T14:46:25.481437Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
3,da41c774-52be-4b7d-9235-d422280fd01d,ecephys_714748_2024-06-24_12-52-23_nwb_2026-08...,714748,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-12-01,Male,2024-06-24T12:52:23-07:00,2024-06-24T14:59:27.907510Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
4,678d3a97-d1f2-4533-a7e0-1300fed47cfb,ecephys_667252_2023-09-28_15-00-38_nwb_2026-08...,667252,wt/wt,2023-01-27,Female,2023-09-28T15:00:38-07:00,2023-09-28T17:03:03.333877Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
5,fb28d3a6-907e-41a6-93b1-dfbe6398f838,ecephys_715710_2024-07-16_12-58-34_nwb_2026-08...,715710,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-12-07,Male,2024-07-16T12:58:34-07:00,2024-07-16T15:05:31.280219Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
6,ffa07448-b91d-4bdf-b3ab-9e6f2c5a8b4d,ecephys_708016_2024-04-29_12-59-12_nwb_2026-08...,708016,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-10-18,Male,2024-04-29T12:59:12-07:00,2024-04-29T15:00:31.755703Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
7,c79e8903-3af9-475d-a034-1ef5de4e4485,ecephys_741137_2024-10-10_13-15-50_nwb_2026-08...,741137,wt/wt,2024-03-19,Male,2024-10-10T13:15:50-07:00,2024-10-10T15:19:11.275413Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
8,9deb4162-9e9b-4ee7-b5e4-db804fd4fcd5,ecephys_712815_2024-05-22_12-26-32_nwb_2026-08...,712815,wt/wt,2023-11-17,Female,2024-05-22T12:26:32-07:00,2024-05-22T14:23:25.111009Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
9,02d42cc2-b456-41e8-9692-3be0c5df8b8d,ecephys_742903_2024-10-23_14-12-23_nwb_2026-08...,742903,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2024-05-16,Female,2024-10-23T14:12:23-07:00,2024-10-23T16:15:54.652646Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
10,0386d97b-bafe-42cf-ad99-1c8b2401fc1d,ecephys_743199_2024-12-05_12-42-34_nwb_2026-08...,743199,VGAT-ChR2-YFP/wt,2024-05-18,Female,2024-12-05T12:42:34-08:00,2024-12-05T14:39:42.445214Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
11,39fd7f08-ec49-4d00-a58c-407511cc8b7a,ecephys_759434_2025-02-04_12-27-22_nwb_2026-08...,759434,VGAT-ChR2-YFP/wt,2024-08-11,Male,2025-02-04T12:27:22-08:00,2025-02-04T14:24:31.241622Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."

In [45]:
df.sort_values(by='subject_id')

,_id,name,subject_id,genotype,date_of_birth,sex,session_start_time,session_end_time,project_name,modality
0,897335f6-895c-455e-89c4-667d86a4304e,ecephys_662892_2023-08-24_14-28-28_nwb_2026-08...,662892,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2022-12-24,Female,2023-08-24T14:28:28-07:00,2023-08-24T16:28:14.588745Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
2,c4ec72da-c795-4da8-a498-3531a621ddc0,ecephys_664851_2023-11-16_12-54-53_nwb_2026-08...,664851,Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-01-09,Female,2023-11-16T12:54:53-08:00,2023-11-16T14:46:25.481437Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
4,678d3a97-d1f2-4533-a7e0-1300fed47cfb,ecephys_667252_2023-09-28_15-00-38_nwb_2026-08...,667252,wt/wt,2023-01-27,Female,2023-09-28T15:00:38-07:00,2023-09-28T17:03:03.333877Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
6,ffa07448-b91d-4bdf-b3ab-9e6f2c5a8b4d,ecephys_708016_2024-04-29_12-59-12_nwb_2026-08...,708016,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-10-18,Male,2024-04-29T12:59:12-07:00,2024-04-29T15:00:31.755703Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
8,9deb4162-9e9b-4ee7-b5e4-db804fd4fcd5,ecephys_712815_2024-05-22_12-26-32_nwb_2026-08...,712815,wt/wt,2023-11-17,Female,2024-05-22T12:26:32-07:00,2024-05-22T14:23:25.111009Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
1,65c0b92b-02d1-479c-82dd-bf8ff10a9af1,ecephys_713655_2024-08-09_10-41-47_nwb_2026-08...,713655,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-11-23,Male,2024-08-09T10:41:47-07:00,2024-08-09T12:49:52.580059Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
3,da41c774-52be-4b7d-9235-d422280fd01d,ecephys_714748_2024-06-24_12-52-23_nwb_2026-08...,714748,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-12-01,Male,2024-06-24T12:52:23-07:00,2024-06-24T14:59:27.907510Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
5,fb28d3a6-907e-41a6-93b1-dfbe6398f838,ecephys_715710_2024-07-16_12-58-34_nwb_2026-08...,715710,Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2023-12-07,Male,2024-07-16T12:58:34-07:00,2024-07-16T15:05:31.280219Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
7,c79e8903-3af9-475d-a034-1ef5de4e4485,ecephys_741137_2024-10-10_13-15-50_nwb_2026-08...,741137,wt/wt,2024-03-19,Male,2024-10-10T13:15:50-07:00,2024-10-10T15:19:11.275413Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
9,02d42cc2-b456-41e8-9692-3be0c5df8b8d,ecephys_742903_2024-10-23_14-12-23_nwb_2026-08...,742903,Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt,2024-05-16,Female,2024-10-23T14:12:23-07:00,2024-10-23T16:15:54.652646Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
10,0386d97b-bafe-42cf-ad99-1c8b2401fc1d,ecephys_743199_2024-12-05_12-42-34_nwb_2026-08...,743199,VGAT-ChR2-YFP/wt,2024-05-18,Female,2024-12-05T12:42:34-08:00,2024-12-05T14:39:42.445214Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."
11,39fd7f08-ec49-4d00-a58c-407511cc8b7a,ecephys_759434_2025-02-04_12-27-22_nwb_2026-08...,759434,VGAT-ChR2-YFP/wt,2024-08-11,Male,2025-02-04T12:27:22-08:00,2025-02-04T14:24:31.241622Z,Dynamic Routing,"[Extracellular electrophysiology, Behavior, Be..."

In [51]:
df.to_csv('/data/metadata/dynamic_routing_metadata.csv', index=False)