In [1]:
import pandas as pd 
import numpy as np
from datetime import datetime, date

In [2]:
from aind_data_access_api.document_db import MetadataDbClient

API_GATEWAY_HOST = "api.allenneuraldynamics.org"
DATABASE = 'metadata_index'
COLLECTION = 'data_assets'

docdb_api_client = MetadataDbClient(
   host=API_GATEWAY_HOST,
   database=DATABASE,
   collection=COLLECTION,
)
print(docdb_api_client._base_url)

https://api.allenneuraldynamics.org/v1/metadata_index/data_assets

In [16]:
aggregate = [
  {
    "$match": {
      "data_description.project_name": "V1 Deep Dive", 
      "name": {"$regex": "filtered"},
      "processing.data_processes": {
        "$elemMatch": {
          "name": "Filter NWB values",
        }
      }
  },
  }
  ,
  {
    "$project": {
      "name": 1, 
      "subject_id": "$data_description.subject_id",
      "genotype": "$subject.subject_details.genotype", 
      "date_of_birth": "$subject.subject_details.date_of_birth", 
      "sex": "$subject.subject_details.sex", 
      "session_time": "$acquisition.acquisition_start_time",
      "project_name": "$data_description.project_name", 
      "modality": "$data_description.modalities.name",
      "column": { "$arrayElemAt": ["$data_description.tags", 0] },
      "volume": { "$arrayElemAt": ["$data_description.tags", 1] }
    }
  },
]
    
records = docdb_api_client.aggregate_docdb_records(
    pipeline = aggregate,
)

In [18]:
records = [r for r in records if 'Electron microscopy' not in r['modality']]
df = pd.DataFrame(records)

df['session_date'] = df.apply(lambda x: datetime.fromisoformat(x['session_time']).date(), axis=1)
df['session_time'] = df.apply(lambda x: datetime.fromisoformat(x['session_time']).time(), axis=1)
df['date_of_birth'] = df.apply(lambda x: datetime.strptime(x['date_of_birth'], '%Y-%m-%d').date(), axis=1)
df['age'] = df.apply(lambda x: (x['session_date'] - x['date_of_birth']).days, axis=1)

df['column'] = df.apply(lambda x: int(x['column'].split(' ')[-1]), axis=1)
df['volume'] = df.apply(lambda x: int(x['volume'].split(' ')[-1]), axis=1)

df['golden_mouse'] = False
df.loc[df.subject_id=='409828', 'golden_mouse'] = True

order = ['project_name','_id','name','subject_id','golden_mouse','genotype','date_of_birth','sex','modality',
         'session_date','age','session_time','column','volume']
df = df[order]

df

,project_name,_id,name,subject_id,golden_mouse,genotype,date_of_birth,sex,modality,session_date,age,session_time,column,volume
0,V1 Deep Dive,98ce8fa1-97f2-40c3-879b-0e99db3abe81,409828_2018-11-29_13-42-04_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-29,149,13:42:04.672510,5,2
1,V1 Deep Dive,b1e7cf7c-bb52-42c9-9dde-54e7594b3ae2,409828_2018-12-13_15-10-05_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-13,163,15:10:05.562960,1,3
2,V1 Deep Dive,2cb93697-c954-4835-9c17-6deed1cf1fb5,409828_2018-12-14_13-14-42_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-14,164,13:14:42.634500,1,4
3,V1 Deep Dive,5aac054c-c0ce-4c19-94e9-8135f047fa62,409828_2018-12-14_14-47-35_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-14,164,14:47:35.097180,1,5
4,V1 Deep Dive,7f7ef7f3-90c4-45d6-b3a4-fa7bf4579be6,416296_2018-11-05_14-13-21_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-05,91,14:13:21.053750,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,V1 Deep Dive,63783ce0-8d69-438e-8e35-73fb8fd5d8c7,438833_2019-03-25_15-10-31_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-25,114,15:10:31.659070,3,3
98,V1 Deep Dive,a18d9824-37aa-46ce-8ea6-f807f6795622,438833_2019-03-26_13-10-05_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-26,115,13:10:05.286770,4,2
99,V1 Deep Dive,c17510e6-31b7-4001-8788-fe8e8ed30269,438833_2019-03-26_14-44-46_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-26,115,14:44:46.601660,4,3
100,V1 Deep Dive,de0aad16-7644-443a-83dc-029bc7342354,438833_2019-03-27_11-33-05_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-27,116,11:33:05.464370,5,2
101,V1 Deep Dive,a298fad0-6033-4537-8946-f265105d9738,438833_2019-03-28_13-07-35_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-28,117,13:07:35.360740,3,5

In [25]:
len(df[df.subject_id == '409828'].sort_values(by='session_date', ascending=False))

28

In [34]:
df[df.subject_id == '409828'].sort_values(by=['column', 'volume', 'session_date'], ascending=False)

,project_name,_id,name,subject_id,golden_mouse,genotype,date_of_birth,sex,modality,session_date,age,session_time,column,volume
53,V1 Deep Dive,c24b6f01-05d0-4721-ae23-d48030857403,409828_2018-12-12_10-53-44_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-12,162,10:53:44.705010,5,5
51,V1 Deep Dive,699e4dcf-70fc-4db2-b438-54f55c606027,409828_2018-12-11_16-12-21_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-11,161,16:12:21.396890,5,4
50,V1 Deep Dive,3c01dc6a-e872-4a1b-a54d-c4781cb5f44e,409828_2018-12-04_15-27-53_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-04,154,15:27:53.082660,5,3
0,V1 Deep Dive,98ce8fa1-97f2-40c3-879b-0e99db3abe81,409828_2018-11-29_13-42-04_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-29,149,13:42:04.672510,5,2
65,V1 Deep Dive,6592ac98-b4ac-4102-9237-8d9063817f15,409828_2018-11-26_11-16-25_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-26,146,11:16:25.373720,5,1
69,V1 Deep Dive,4a87c914-a62c-4b2a-91dd-de97523d9c70,409828_2018-12-11_14-40-36_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-11,161,14:40:36.449080,4,5
67,V1 Deep Dive,7dae9405-e14a-4647-b3bd-c2906696387b,409828_2018-12-03_15-56-23_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-03,153,15:56:23.139770,4,4
14,V1 Deep Dive,2149df96-789c-40d2-942c-988fc4c48d3d,409828_2018-12-03_14-25-24_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-03,153,14:25:24.632480,4,3
64,V1 Deep Dive,5690e017-7c61-4570-8128-182ffc1d36c6,409828_2018-11-21_10-56-07_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-21,141,10:56:07.266840,4,2
82,V1 Deep Dive,2f3d1e9f-4e29-4701-8da3-5695db905631,409828_2018-11-21_09-22-23_filtered_2026-04-16...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-21,141,09:22:23.259970,4,1
16,V1 Deep Dive,9d54efdd-135f-4a2c-8bf9-600867ff9783,409828_2018-12-10_15-28-55_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-10,160,15:28:55.711250,3,5
68,V1 Deep Dive,b25313a3-fc21-4f9d-a130-2331ee64af23,409828_2018-12-10_14-02-21_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-10,160,14:02:21.248450,3,4
79,V1 Deep Dive,82b82a66-fe0d-4ffa-a583-cc3df43d6c83,409828_2018-11-28_10-54-56_filtered_2026-04-10...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-28,148,10:54:56.809310,3,3
80,V1 Deep Dive,08f4622e-efb0-4892-81cb-88d46ab20b13,409828_2018-11-28_10-54-56_filtered_2026-04-16...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-28,148,10:54:56.809310,3,3
52,V1 Deep Dive,9fbacdd9-1500-4f65-9bbe-246d5fc71af2,409828_2018-11-20_12-12-08_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-20,140,12:12:08.089640,3,2
84,V1 Deep Dive,53f29b50-0214-430d-a9fd-ca62a4c93f03,409828_2018-11-20_12-12-08_filtered_2026-05-15...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-20,140,12:12:08.089640,3,2
12,V1 Deep Dive,96f14e2d-ae9e-4237-acfc-634feb17ff38,409828_2018-11-20_10-42-45_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-20,140,10:42:45.603660,3,1
83,V1 Deep Dive,0e974d11-05d9-4824-bcf9-829a8bb86e32,409828_2018-11-20_10-42-45_filtered_2026-05-15...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-20,140,10:42:45.603660,3,1
15,V1 Deep Dive,da7b7b39-5a63-4917-b9ec-21474da48900,409828_2018-12-05_14-40-32_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-05,155,14:40:32.706220,2,4
13,V1 Deep Dive,82f2512c-6484-46bc-9717-f7b9bbcdabca,409828_2018-11-27_12-29-05_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-27,147,12:29:05.453040,2,3
66,V1 Deep Dive,cfdc4638-f40c-4ff7-b1c8-93e2b4b76d6d,409828_2018-11-27_11-01-58_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-27,147,11:01:58.469640,2,2
11,V1 Deep Dive,c975f944-796f-4d9b-af0d-29252a22dae7,409828_2018-11-06_14-02-59_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-06,126,14:02:59.889330,2,1
85,V1 Deep Dive,8a37ef2e-ae64-4673-abc1-7c69b18e186a,409828_2018-11-06_14-02-59_filtered_2026-05-15...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-11-06,126,14:02:59.889330,2,1
3,V1 Deep Dive,5aac054c-c0ce-4c19-94e9-8135f047fa62,409828_2018-12-14_14-47-35_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-14,164,14:47:35.097180,1,5
2,V1 Deep Dive,2cb93697-c954-4835-9c17-6deed1cf1fb5,409828_2018-12-14_13-14-42_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-14,164,13:14:42.634500,1,4
1,V1 Deep Dive,b1e7cf7c-bb52-42c9-9dde-54e7594b3ae2,409828_2018-12-13_15-10-05_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-13,163,15:10:05.562960,1,3
71,V1 Deep Dive,99fb8537-40f8-4960-ad02-dd723124e7d6,409828_2018-12-13_13-21-39_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-13,163,13:21:39.888000,1,2
70,V1 Deep Dive,2b93bc7c-c2dc-4347-9279-80f5c3e7ddb0,409828_2018-12-12_12-24-18_filtered_2026-04-09...,409828,True,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-07-03,Male,"[Planar optical physiology, Behavior videos]",2018-12-12,162,12:24:18.963730,1,1

In [29]:
len(df[df.subject_id == '416296'].sort_values(by='session_date', ascending=False))

25

In [35]:
df[df.subject_id == '416296'].sort_values(by=['column', 'volume', 'session_date'], ascending=False)

,project_name,_id,name,subject_id,golden_mouse,genotype,date_of_birth,sex,modality,session_date,age,session_time,column,volume
86,V1 Deep Dive,b87ab715-b5ad-45fc-adfc-150e6f18a17e,416296_2018-12-05_13-02-39_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-05,121,13:02:39.575900,5,5
46,V1 Deep Dive,a9a080ed-3b22-4ab9-a390-a45c4d726468,416296_2018-12-05_11-31-44_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-05,121,11:31:44.290780,5,4
35,V1 Deep Dive,92817871-dc1e-4638-9231-319beba07e30,416296_2018-12-04_13-45-25_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-04,120,13:45:25.427340,5,3
43,V1 Deep Dive,22212e61-9a14-462f-8670-0d615d362198,416296_2018-12-04_12-17-47_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-04,120,12:17:47.000730,5,2
7,V1 Deep Dive,aaf89272-aee4-4b77-97c7-0b9e0850a045,416296_2018-11-14_10-20-29_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-14,100,10:20:29.147870,5,1
36,V1 Deep Dive,5e07581c-6d0d-41d6-97d8-aceebfaa4d92,416296_2018-12-07_13-19-39_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-07,123,13:19:39.881600,4,5
34,V1 Deep Dive,496645d0-ef98-4e55-a199-810bf683d157,416296_2018-12-03_12-42-43_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-03,119,12:42:43.916490,4,4
17,V1 Deep Dive,96b081b5-a74a-4b8e-b179-d1daff8c0066,416296_2018-12-03_11-11-50_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-03,119,11:11:50.005770,4,3
33,V1 Deep Dive,10638d89-8804-4a2f-a1a1-627530da7250,416296_2018-11-30_14-41-49_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-30,116,14:41:49.316520,4,2
54,V1 Deep Dive,37ca66cc-8f20-41fc-be0c-01989d390b6b,416296_2018-11-16_12-27-27_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-16,102,12:27:27.887290,4,1
72,V1 Deep Dive,c35bc5c3-cb3c-4c1e-8c86-c25608a4ea46,416296_2018-11-30_13-10-57_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-30,116,13:10:57.408410,3,5
55,V1 Deep Dive,4520a865-9d5e-427f-b758-986658acca8e,416296_2018-11-19_12-17-21_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-19,105,12:17:21.748990,3,4
10,V1 Deep Dive,9dbc1cf4-4d67-4b39-ba4e-f6722cf2753a,416296_2018-11-19_10-44-43_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-19,105,10:44:43.514810,3,3
6,V1 Deep Dive,ff811631-426b-428d-9fd4-5e4248d04a25,416296_2018-11-06_12-19-49_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-06,92,12:19:49.261470,3,2
5,V1 Deep Dive,1c10fcee-9110-4f63-804d-23c126119174,416296_2018-11-06_10-41-36_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-06,92,10:41:36.657640,3,1
32,V1 Deep Dive,a1460a2f-6b81-47bb-a244-c6a1ad77f782,416296_2018-11-29_12-08-40_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-29,115,12:08:40.014190,2,5
56,V1 Deep Dive,9472cf2d-ce24-4afa-9e11-06d797d70e7a,416296_2018-11-29_10-32-33_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-29,115,10:32:33.934770,2,4
76,V1 Deep Dive,be92f9fe-ea81-4f77-97fa-3595b27f53a1,416296_2018-11-15_12-10-20_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-15,101,12:10:20.600320,2,3
8,V1 Deep Dive,53dbb74e-a5c8-4084-a1ed-2f5fcd30ebfc,416296_2018-11-15_10-41-12_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-15,101,10:41:12.103130,2,2
4,V1 Deep Dive,7f7ef7f3-90c4-45d6-b3a4-fa7bf4579be6,416296_2018-11-05_14-13-21_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-05,91,14:13:21.053750,2,1
87,V1 Deep Dive,58453911-b619-49dd-9b5b-8808031a67de,416296_2018-12-11_12-57-17_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-11,127,12:57:17.432770,1,5
73,V1 Deep Dive,b87a7c06-be2d-4e4b-942e-48487e059ac8,416296_2018-12-11_11-29-26_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-11,127,11:29:26.512350,1,4
37,V1 Deep Dive,21bc365b-d2fb-4f7b-b585-7dbd38570999,416296_2018-12-10_12-22-21_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-10,126,12:22:21.985070,1,3
18,V1 Deep Dive,28235492-e643-40fc-b47c-57317537794b,416296_2018-12-10_10-42-05_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-12-10,126,10:42:05.206960,1,2
9,V1 Deep Dive,a375578f-a84d-4726-9531-6f9fd742738b,416296_2018-11-16_10-57-02_filtered_2026-04-09...,416296,False,Camk2a-tTA/wt;tetO-GCaMP6s/wt,2018-08-06,Female,"[Planar optical physiology, Behavior videos]",2018-11-16,102,10:57:02.824560,1,1

In [37]:
len(df[df.subject_id == '427836'].sort_values(by='session_date', ascending=False))

24

In [36]:
df[df.subject_id == '427836'].sort_values(by=['column', 'volume', 'session_date'], ascending=False)

,project_name,_id,name,subject_id,golden_mouse,genotype,date_of_birth,sex,modality,session_date,age,session_time,column,volume
47,V1 Deep Dive,3ded8d2c-481b-4d9a-ac09-9dbc9b387120,427836_2019-04-30_15-10-52_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-30,204,15:10:52.762930,5,5
59,V1 Deep Dive,54fb413b-689b-423e-9d1a-74cb12552a7e,427836_2019-04-25_13-49-39_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-25,199,13:49:39.163550,5,4
44,V1 Deep Dive,64864d19-03b7-4529-acbd-8853b1ad3458,427836_2019-04-25_12-16-58_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-25,199,12:16:58.240890,5,3
88,V1 Deep Dive,c4cf0319-da99-41aa-962b-d01a504ef3db,427836_2019-04-18_13-14-46_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-18,192,13:14:46.884560,5,2
42,V1 Deep Dive,63e07fd1-fd55-478d-abe8-0221215a487d,427836_2019-04-18_11-48-17_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-18,192,11:48:17.399500,5,1
81,V1 Deep Dive,382ceffb-75b7-4a29-930a-5da423ffa09a,427836_2019-04-29_15-02-53_filtered_2026-04-16...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-29,203,15:02:53.992910,4,5
90,V1 Deep Dive,b47e2543-329c-4bb1-b506-8f0739d447f6,427836_2019-04-29_13-36-17_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-29,203,13:36:17.106870,4,4
89,V1 Deep Dive,d54521e9-8942-4401-a0ed-775a67288e09,427836_2019-04-24_13-06-45_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-24,198,13:06:45.257460,4,3
21,V1 Deep Dive,d5a76f58-b4a4-46cd-a9f9-1adcf60fefd9,427836_2019-04-17_14-40-45_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-17,191,14:40:45.546830,4,2
77,V1 Deep Dive,fb846747-f00b-4336-bc6f-c46ae8843e02,427836_2019-04-17_13-08-38_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-17,191,13:08:38.689270,4,1
91,V1 Deep Dive,c0a453bd-72ea-4ce4-a166-d2e9e6ebfd84,427836_2019-04-30_10-29-22_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-30,204,10:29:22.878560,3,5
23,V1 Deep Dive,abbadd13-bcf0-44aa-9c2f-6b7853482a46,427836_2019-04-23_14-29-17_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-23,197,14:29:17.154970,3,4
58,V1 Deep Dive,751630d8-b023-40f5-958c-b5ed2645b12f,427836_2019-04-23_13-02-41_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-23,197,13:02:41.258130,3,3
20,V1 Deep Dive,91e2cc7b-396d-4900-a276-21ae6889bd9a,427836_2019-04-16_15-58-17_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-16,190,15:58:17.756860,3,2
41,V1 Deep Dive,73a57bf6-84f7-474c-bfb8-bc1bd3a4772b,427836_2019-04-16_14-31-12_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-16,190,14:31:12.876370,3,1
24,V1 Deep Dive,b3094bfe-8564-4d55-921e-d9573b1d7048,427836_2019-04-26_14-23-32_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-26,200,14:23:32.162710,2,5
60,V1 Deep Dive,a28517a7-1fd2-4def-aab2-2e451260b186,427836_2019-04-26_12-54-40_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-26,200,12:54:40.332660,2,4
22,V1 Deep Dive,dfd234ab-0b25-4375-b365-99d00b38785d,427836_2019-04-22_12-36-06_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-22,196,12:36:06.598670,2,2
19,V1 Deep Dive,12505513-8023-4d35-91cd-dd8cad9b4ddd,427836_2019-04-15_13-59-10_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-15,189,13:59:10.329630,2,1
40,V1 Deep Dive,b021092f-2332-4e75-803a-72ba94dd7c5c,427836_2019-04-15_12-26-38_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-04-15,189,12:26:38.079460,1,5
57,V1 Deep Dive,5bd3a377-f2d7-413c-986f-98ea1d91fb7c,427836_2019-03-21_12-30-14_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-03-21,164,12:30:14.786380,1,4
39,V1 Deep Dive,e910fa71-67fa-401b-a646-24b9f4a56313,427836_2019-02-20_15-19-38_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-02-20,135,15:19:38.470320,1,3
38,V1 Deep Dive,258b3f41-b16e-46cc-90bd-12a7be8acc9c,427836_2019-02-20_13-54-22_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-02-20,135,13:54:22.282920,1,2
74,V1 Deep Dive,9314f10f-8aad-47d2-926d-e302fb6a2e10,427836_2019-02-19_15-16-54_filtered_2026-04-09...,427836,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-10-08,Female,"[Planar optical physiology, Behavior videos]",2019-02-19,134,15:16:54.173730,1,1

In [28]:
len(df[df.subject_id == '438833'].sort_values(by='session_date', ascending=False))

25

In [38]:
df[df.subject_id == '438833'].sort_values(by=['column', 'volume', 'session_date'], ascending=False)

,project_name,_id,name,subject_id,golden_mouse,genotype,date_of_birth,sex,modality,session_date,age,session_time,column,volume
31,V1 Deep Dive,89f2d5e7-d631-488e-93b4-ca6c1191d759,438833_2019-04-01_16-10-33_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-04-01,121,16:10:33.869560,5,5
30,V1 Deep Dive,bddf33d3-17c7-4095-9649-92e5b712a866,438833_2019-04-01_14-39-42_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-04-01,121,14:39:42.230830,5,4
27,V1 Deep Dive,40fd8a56-ce65-42fb-815f-f39a46e4ebb9,438833_2019-03-27_14-24-07_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-27,116,14:24:07.041320,5,3
100,V1 Deep Dive,de0aad16-7644-443a-83dc-029bc7342354,438833_2019-03-27_11-33-05_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-27,116,11:33:05.464370,5,2
62,V1 Deep Dive,89a2b07f-a080-44a1-8262-f25b39563c1d,438833_2019-03-21_14-08-14_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-21,110,14:08:14.261290,5,1
29,V1 Deep Dive,9fd5eaca-802c-448a-901f-e2dcbf1b1d50,438833_2019-03-29_14-55-11_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-29,118,14:55:11.866780,4,5
28,V1 Deep Dive,065d3b4e-c12a-4bd8-b25d-b020ac671ff0,438833_2019-03-29_13-14-43_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-29,118,13:14:43.095060,4,4
99,V1 Deep Dive,c17510e6-31b7-4001-8788-fe8e8ed30269,438833_2019-03-26_14-44-46_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-26,115,14:44:46.601660,4,3
98,V1 Deep Dive,a18d9824-37aa-46ce-8ea6-f807f6795622,438833_2019-03-26_13-10-05_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-26,115,13:10:05.286770,4,2
61,V1 Deep Dive,48314eaf-ce8d-4f91-9d36-a8c683c0edde,438833_2019-03-20_15-17-34_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-20,109,15:17:34.583240,4,1
101,V1 Deep Dive,a298fad0-6033-4537-8946-f265105d9738,438833_2019-03-28_13-07-35_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-28,117,13:07:35.360740,3,5
78,V1 Deep Dive,7ecf275d-9b7f-419c-a9a8-c5cdcc6397dc,438833_2019-03-28_11-31-08_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-28,117,11:31:08.475210,3,4
97,V1 Deep Dive,63783ce0-8d69-438e-8e35-73fb8fd5d8c7,438833_2019-03-25_15-10-31_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-25,114,15:10:31.659070,3,3
96,V1 Deep Dive,ef15be4e-8a1b-4a61-9b9d-91a859aaa758,438833_2019-03-25_13-35-06_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-25,114,13:35:06.011390,3,2
26,V1 Deep Dive,d2b46c71-a324-47f3-9c95-0a428ae11c8f,438833_2019-03-19_15-15-54_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-19,108,15:15:54.236360,3,1
49,V1 Deep Dive,7171b582-a980-4856-aeb0-89e66e2d7799,438833_2019-04-02_12-00-00_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-04-02,122,12:00:00.963460,2,5
63,V1 Deep Dive,915b1a6a-dd97-4ef8-a5c4-21d62b16094b,438833_2019-03-22_14-15-29_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-22,111,14:15:29.744600,2,4
95,V1 Deep Dive,83581600-25fe-4b22-ba0b-290195264a91,438833_2019-03-22_12-48-55_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-22,111,12:48:55.564300,2,3
25,V1 Deep Dive,4bfde708-08de-41bf-9cd1-be61294f4900,438833_2019-03-15_15-31-03_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-15,104,15:31:03.507360,2,2
48,V1 Deep Dive,a9311a83-2b66-45c4-b250-888d88680df7,438833_2019-03-14_15-45-30_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-14,103,15:45:30.804180,2,1
94,V1 Deep Dive,e89e6297-54a6-47aa-b291-7a2425f3059b,438833_2019-03-14_14-18-27_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-14,103,14:18:27.144330,1,5
75,V1 Deep Dive,88bc1c4b-8580-4060-abd7-7022cceecfb6,438833_2019-03-13_15-17-01_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-13,102,15:17:01.062660,1,4
93,V1 Deep Dive,f609d295-ef09-4723-8385-24e7e273df2e,438833_2019-03-13_13-47-04_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-13,102,13:47:04.198890,1,3
92,V1 Deep Dive,3366caf5-15d1-4458-a60e-bde5bef83b57,438833_2019-03-12_15-10-30_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-12,101,15:10:30.850270,1,2
45,V1 Deep Dive,79bed16e-f321-460e-9790-271b5fd2c3a1,438833_2019-03-08_14-59-45_filtered_2026-04-09...,438833,False,Slc17a7-IRES2-Cre/wt;Camk2a-tTA/wt;Ai94(TITL-G...,2018-12-01,Male,"[Planar optical physiology, Behavior videos]",2019-03-08,97,14:59:45.383070,1,1

In [21]:
df.to_csv('/data/metadata/V1DD_metadata.csv', index= False)